/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterPsychologistRouteImport } from './routes/register-psychologist'
import { Route as RegisterPatientRouteImport } from './routes/register-patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMedicalRecordsRouteImport } from './routes/_authenticated/medical-records'
import { Route as AuthenticatedInitialAssessmentRouteImport } from './routes/_authenticated/initial-assessment'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin-dashboard'

const RegisterPsychologistRoute = RegisterPsychologistRouteImport.update({
  id: '/register-psychologist',
  path: '/register-psychologist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPatientRoute = RegisterPatientRouteImport.update({
  id: '/register-patient',
  path: '/register-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicalRecordsRoute =
  AuthenticatedMedicalRecordsRouteImport.update({
    id: '/medical-records',
    path: '/medical-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInitialAssessmentRoute =
  AuthenticatedInitialAssessmentRouteImport.update({
    id: '/initial-assessment',
    path: '/initial-assessment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin-dashboard',
    path: '/admin-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-patient': typeof RegisterPatientRoute
  '/register-psychologist': typeof RegisterPsychologistRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/initial-assessment': typeof AuthenticatedInitialAssessmentRoute
  '/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-patient': typeof RegisterPatientRoute
  '/register-psychologist': typeof RegisterPsychologistRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/initial-assessment': typeof AuthenticatedInitialAssessmentRoute
  '/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register-patient': typeof RegisterPatientRoute
  '/register-psychologist': typeof RegisterPsychologistRoute
  '/_authenticated/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRoute
  '/_authenticated/initial-assessment': typeof AuthenticatedInitialAssessmentRoute
  '/_authenticated/medical-records': typeof AuthenticatedMedicalRecordsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register-patient'
    | '/register-psychologist'
    | '/admin-dashboard'
    | '/appointments'
    | '/chatbot'
    | '/dashboard'
    | '/evaluations'
    | '/initial-assessment'
    | '/medical-records'
    | '/messages'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register-patient'
    | '/register-psychologist'
    | '/admin-dashboard'
    | '/appointments'
    | '/chatbot'
    | '/dashboard'
    | '/evaluations'
    | '/initial-assessment'
    | '/medical-records'
    | '/messages'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register-patient'
    | '/register-psychologist'
    | '/_authenticated/admin-dashboard'
    | '/_authenticated/appointments'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/evaluations'
    | '/_authenticated/initial-assessment'
    | '/_authenticated/medical-records'
    | '/_authenticated/messages'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterPatientRoute: typeof RegisterPatientRoute
  RegisterPsychologistRoute: typeof RegisterPsychologistRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-psychologist': {
      id: '/register-psychologist'
      path: '/register-psychologist'
      fullPath: '/register-psychologist'
      preLoaderRoute: typeof RegisterPsychologistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-patient': {
      id: '/register-patient'
      path: '/register-patient'
      fullPath: '/register-patient'
      preLoaderRoute: typeof RegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medical-records': {
      id: '/_authenticated/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/initial-assessment': {
      id: '/_authenticated/initial-assessment'
      path: '/initial-assessment'
      fullPath: '/initial-assessment'
      preLoaderRoute: typeof AuthenticatedInitialAssessmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-dashboard': {
      id: '/_authenticated/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRoute
  AuthenticatedInitialAssessmentRoute: typeof AuthenticatedInitialAssessmentRoute
  AuthenticatedMedicalRecordsRoute: typeof AuthenticatedMedicalRecordsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRoute,
  AuthenticatedInitialAssessmentRoute: AuthenticatedInitialAssessmentRoute,
  AuthenticatedMedicalRecordsRoute: AuthenticatedMedicalRecordsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterPatientRoute: RegisterPatientRoute,
  RegisterPsychologistRoute: RegisterPsychologistRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
